### ISSUE TITLE
Error converting arxml

### ISSUE THREAD

**Issue by nostar** [ebroecker/canmatrix#104]
When running the following command on an arxml file I get the following error:

```
canconvert --deleteZeroSignals -vv file.arxml file.dbc
INFO - formats - xlsx is not supported
INFO - formats - yaml is not supported
INFO - convert - Importing file.arxml ... 
DEBUG - arxml - Read arxml ...
DEBUG - arxml -  Done

DEBUG - arxml - Build arTree ...
DEBUG - arxml -  Done

DEBUG - arxml - DEBUG 160 frames in arxml...
DEBUG - arxml - DEBUG 160 can-frame-triggering in arxml...
DEBUG - arxml - DEBUG 0 SIGNAL-TO-PDU-MAPPINGS in arxml...
DEBUG - arxml - DEBUG 644 I-SIGNAL-TO-I-PDU-MAPPING in arxml...

---Long list of processing frames/signals, here a few examples---

DEBUG - arxml - processing Frame:Frame01_On_CAN_Cluster
DEBUG - arxml - PDU01_On_CAN_Cluster
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
...
DEBUG - arxml - processing Frame: Frame02_On_CAN_Cluster
DEBUG - arxml - PDU02
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - getSignals: found I-SIGNAL-GROUP 
DEBUG - arxml - getSignals: found I-SIGNAL-GROUP 
DEBUG - arxml - getSignals: found I-SIGNAL-GROUP 
...
DEBUG - arxml - processing Frame: Frame03_On_CAN_Cluster
DEBUG - arxml - PDU03
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - getSignals: found I-SIGNAL-GROUP 
DEBUG - arxml - processing Frame: Frame04_On_CAN_Cluster
DEBUG - arxml - PDU04
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
DEBUG - arxml - No Compmethod found!! - try alternate scheme.
Traceback (most recent call last):
  File "/usr/bin/canconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/canmatrix/convert.py", line 294, in main
    convert(infile, outfileName, **cmdlineOptions.__dict__)
  File "/usr/lib/python2.7/site-packages/canmatrix/convert.py", line 41, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "/usr/lib/python2.7/site-packages/canmatrix/formats.py", line 54, in loadp
    return load(fileObject, importType, **options)
  File "/usr/lib/python2.7/site-packages/canmatrix/formats.py", line 64, in load
    dbs = moduleInstance.load(fileObject, **options)
  File "/usr/lib/python2.7/site-packages/canmatrix/arxml.py", line 1553, in load
    ns))
  File "/usr/lib/python2.7/site-packages/canmatrix/arxml.py", line 1301, in getFrame
    getSignals(pdusigmapping, newFrame, arDict, ns, None)
  File "/usr/lib/python2.7/site-packages/canmatrix/arxml.py", line 1088, in getSignals
    if motorolla.text == 'MOST-SIGNIFICANT-BYTE-LAST':
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by nostar** [comment]
Works good now.
