### ISSUE TITLE
issue in converting an arxml file to dbc

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#169]
Hi, I am getting this below error when I tried to convert arxml file to dbc. Could you please help

C:\LegacyApp\Python27\Scripts>canconvert.py xMA_17022_EC.arxml test.dbc
Traceback (most recent call last):
  File "C:\LegacyApp\Python27\Scripts\canconvert.py", line 9, in <module>
    load_entry_point('canmatrix==0.6', 'console_scripts', 'canconvert')()
  File "build\bdist.win-amd64\egg\canmatrix\convert.py", line 294, in main
  File "build\bdist.win-amd64\egg\canmatrix\convert.py", line 41, in convert
  File "build\bdist.win-amd64\egg\canmatrix\formats.py", line 54, in loadp
  File "build\bdist.win-amd64\egg\canmatrix\formats.py", line 64, in load
  File "build\bdist.win-amd64\egg\canmatrix\arxml.py", line 1553, in load
  File "build\bdist.win-amd64\egg\canmatrix\arxml.py", line 1160, in getFrame
AttributeError: 'NoneType' object has no attribute 'tag'

**Comment by ebroecker** [comment]
did you try with current development branch already?

**Comment by Jayanthdj** [comment]
Ok, I will check and let you know

**Comment by Jayanthdj** [comment]
With the current devpath also I am getting the same error :(

C:\LegacyApp\Python27\Scripts>canconvert-script.py ES.arxml test.arxml
Traceback (most recent call last):
  File "C:\LegacyApp\Python27\Scripts\canconvert-script.py", line 9, in <module>
    load_entry_point('canmatrix==0+unknown', 'console_scripts', 'canconvert')()
  File "build\bdist.win-amd64\egg\canmatrix\convert.py", line 393, in main
  File "build\bdist.win-amd64\egg\canmatrix\convert.py", line 41, in convert
  File "build\bdist.win-amd64\egg\canmatrix\formats.py", line 64, in loadp
  File "build\bdist.win-amd64\egg\canmatrix\formats.py", line 74, in load
  File "build\bdist.win-amd64\egg\canmatrix\arxml.py", line 1559, in load
  File "build\bdist.win-amd64\egg\canmatrix\arxml.py", line 1209, in getFrame
AttributeError: 'NoneType' object has no attribute 'tag'

**Comment by ebroecker** [comment]
well - could you test again?

**Comment by Jayanthdj** [comment]
Hi Edward, I used the current development package. but still the same issue. Could you please help

**Comment by Jayanthdj** [comment]
Sorry again. Got below error.
TypeError: getSignals() takes exactly 6 arguments (5 given)

**Comment by ebroecker** [comment]
is this issue still a problem or can I close?

**Comment by Jayanthdj** [comment]
HI, I am able to convert those files , Yes, you can close it. Thank you so  much.!

**Comment by ebroecker** [comment]
OK, thanks

**Comment by shubhamthakare** [comment]
Hi,I wanted to convert arxml to dbc.

Please help me
