### ISSUE TITLE
cancompare xxx.dbc (old) xxx.dbc (new) - error

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#33]
cancompare (latest master from 3rd of Feb 2016):
cancompare xxx.dbc xxx.dbc

Traceback (most recent call last):
  File "/usr/bin/cancompare", line 9, in <module>
    load_entry_point('canmatrix==0.3', 'console_scripts', 'cancompare')()
  File "build/bdist.cygwin-2.3.1-i686/egg/canmatrix/compare.py", line 356, in main
  File "build/bdist.cygwin-2.3.1-i686/egg/canmatrix/compare.py", line 64, in compareDb
  File "build/bdist.cygwin-2.3.1-i686/egg/canmatrix/compare.py", line 206, in compareFrame
  File "build/bdist.cygwin-2.3.1-i686/egg/canmatrix/compare.py", line 268, in compareSignal
TypeError: %d format: a number is required, not unicode

**Comment by ebroecker** [comment]
fixed
