### ISSUE TITLE
XLSX export module: support for complex multiplexers

### ISSUE THREAD

**Issue by mwoco** [ebroecker/canmatrix#403]
When converting DBC files to XLSX I get "ERROR - xlsx - Export complex multiplexers is not supported - ignoring frame …". Could you extent the XLSX export module with complex multiplex support? Thanks!

**Comment by mwoco** [comment]
Thank you for the quick fix! I have been able to test the new version 0.9.1 and it's already working great as messages/signals are not dismissed anymore. ;)

I would like suggest one further modification: With the current code a can message like

 - Multiplexor A
 - Multiplexor B
 - Signal 1 (A = 1)
 - Signal 2 (A = 2)
 - Signal 3 (B = 1)
 - Signal 4 (B = 2)

turns into

 - Multiplexor A (Mode signal:)
 - Multiplexor B (Mode signal:)
 - Signal 1 (Mode 1:)
 - Signal 2 (Mode 2:)
 - Signal 3 (Mode 1:)
 - Signal 4 (Mode 2:)

within the xlsx-file. This way it is not possible to say anymore, which multiplexor (A or B) belongs to each signal. So I would recommend doing something like

 - Multiplexor A (Mode signal)
 - Multiplexor B (Mode signal)
 - Signal 1 (mode A = 1)
 - Signal 2 (mode A = 2)
 - Signal 3 (mode B = 1)
 - Signal 4 (mode B = 2)

Is that possible?

**Comment by ebroecker** [comment]
@mwoco 
Thanks for testing.
Yes, this is why this issue is still open. Till now only the "abort" for "complex multiplexed" was removed.
I'll check your suggestion

**Comment by ebroecker** [comment]
@mwoco did you try branch iss403

**Comment by mwoco** [comment]
Sorry for the delay. I will give it a try at the beginning of January.

**Comment by mwoco** [comment]
I've just tested branch iss403: But the output file looks the same like without your fix. Here is what I did:
 - download ZIP file from https://github.com/ebroecker/canmatrix/tree/iss403 an extract its contents to some directory
 - convert DBC by trying both "src\canmatrix\cli\convert.py" and "examples\convert.py"

**Comment by ebroecker** [comment]
you need to install the new version first:
something like
`python setup.py install`

**Comment by mwoco** [comment]
Ok. I used the install command and then tried to convert a DBC file using "canconvert.exe". This seems to work for a couple of messages and then fails with the following error message:

`Traceback (most recent call last):
  File "...\dbc2xlsx\WinPython64-3.7.4.1Zero\WPy64-3741\python-3.7.4.amd64\Scripts\canconvert-script.py", line 11, in <module>
    load_entry_point('canmatrix==0+unknown', 'console_scripts', 'canconvert')()
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\canmatrix-0+unknown-py3.7.egg\canmatrix\cli\convert.py", line 135, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\canmatrix-0+unknown-py3.7.egg\canmatrix\convert.py", line 214, in convert
    canmatrix.formats.dumpp(out_dbs, out_file_name, **options)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\canmatrix-0+unknown-py3.7.egg\canmatrix\formats\__init__.py", line 135, in dumpp
    dump(db, file_object, export_type, **options)
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\canmatrix-0+unknown-py3.7.egg\canmatrix\formats\__init__.py", line 110, in dump
    module_instance.dump(can_matrix_or_cluster, file_object, **options)  # type: ignore
  File "...\dbc2xlsx\winpython64-3.7.4.1zero\wpy64-3741\python-3.7.4.amd64\lib\site-packages\canmatrix-0+unknown-py3.7.egg\canmatrix\formats\xlsx.py", line 260, in dump
    (frontRow, back_row) = canmatrix.formats.xls_common.get_signal(db, sig, motorola_bit_format)
TypeError: get_signal() missing 1 required positional argument: 'motorola_bit_format'`

**Comment by mwoco** [comment]
Any update on this topic?

**Comment by ebroecker** [comment]
oh - sorry - I forgot to have a look on it...
I'll need to find some time for having a look on it.

**Comment by mwoco** [comment]
Had a chance to look on it meanwhile?

**Comment by ebroecker** [comment]
no - sorry - not yet -
