### ISSUE TITLE
extraction should fail gracefully if no frames are found

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#427]
Hi, when I try to extract based on ecu tx or rx from a dbc, the following trace is generated. I think it already prints out 0 Frames found and should just catch this error internally.

INFO - convert - 0 Frames found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/cli/convert.py", line 136, in <module>
    sys.exit(cli_convert())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/cli/convert.py", line 131, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 210, in convert
    canmatrix.formats.dumpp(out_dbs, out_file_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 135, in dumpp
    dump(db, file_object, export_type, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 110, in dump
    module_instance.dump(can_matrix_or_cluster, file_object, **options)  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/dbc.py", line 250, in dump
    if max([x.cycle_time for x in db.frames]) > 0:
  File "/usr/local/lib/python2.7/dist-packages/future/builtins/new_min_max.py", line 17, in newmax
    return new_min_max(_builtin_max, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/future/builtins/new_min_max.py", line 47, in new_min_max
    raise ValueError('{}() arg is an empty sequence'.format(_builtin_func.__name__))
ValueError: max() arg is an empty sequence

**Comment by ebroecker** [comment]
should be fixed in branch Iss427
