### ISSUE TITLE
ARXML to DBC conversion throws error

### ISSUE THREAD

**Issue by Prabhu6296** [ebroecker/canmatrix#487]
Hi,

When I tried to convert ARXML to dbc using the command "python -m canmatrix.cli.convert -vv someNAME.arxml test.dbc", in the command prompt I got the following error saying:

INFO - convert - Importing someNAME.arxml ...
ERROR - __init__ - This file format is not supported for reading
INFO - convert - done

INFO - convert - Exporting test.dbc ...
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user123\AppData\Roaming\Python\Python37\site-packages\canmatrix\cli\convert.py", line 136, in <module>
    sys.exit(cli_convert())
  File "C:\Program Files\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\user123\AppData\Roaming\Python\Python37\site-packages\canmatrix\cli\convert.py", line 131, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "C:\Users\user123\AppData\Roaming\Python\Python37\site-packages\canmatrix\convert.py", line 46, in convert
    for name in dbs:
TypeError: 'NoneType' object is not iterable.

Notes:

I already have all the pre-requisites installed.
OS - Windows 10
Python 3.7

**Comment by ebroecker** [comment]
did you install the requirements (i.e. lxml?)
https://canmatrix.readthedocs.io/en/latest/installation.html
