### ISSUE TITLE
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>] while converting arxml to dbc

### ISSUE THREAD

**Issue by fe1510** [ebroecker/canmatrix#588]
Hi, I am using canmatrix for converting arxml to dbc.
I met this issue for some ARXML files while canmatrix worked sometimes for other ARXML files. Unfortunately I cannot solve this problem.

I have the issue as the following Traceback.

Traceback (most recent call last):
  File "D:\ETASData\WZX\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ETASData\WZX\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ETASData\WZX\pythonProject\venv\Scripts\canconvert.exe\__main__.py", line 7, in <module>
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\cli\convert.py", line 135, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\convert.py", line 40, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\__init__.py", line 77, in loadp
    return load(fileObject, import_type, key, **options)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\__init__.py", line 94, in load
    dbs = module_instance.load(file_object, **options)  # type: ignore
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\arxml.py", line 1947, in load
    result.update(decode_can_helper(ea, float_factory, ignore_cluster_info))
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\arxml.py", line 1842, in decode_can_help
er
    frame = get_frame(frameTrig, ea, multiplex_translation, float_factory)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\arxml.py", line 1513, in get_frame
    get_signals(pdu_sig_mapping, new_frame, ea, None, float_factory)
  File "d:\etasdata\wzx\pythonproject\venv\lib\site-packages\canmatrix\formats\arxml.py", line 1234, in get_signals
    new_signal.initial_value = float_factory(initvalue.text)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

Best Regards
fe1510

**Comment by atpAlon** [comment]
I have met the same problem, and i modify the guess_value() function of site-packages\canmatrix\utils.py as this:
`    if sys.version_info >= (3, 0):
        text_value = text_value.casefold()
    else:
        text_value = text_value.lower()
    if text_value in ["false", "off"]:
        return "0"
    elif text_value in ["true", "on"]:
        return "1"
    elif '0x' in text_value:
        return str(int(text_value,0))
    return text_value`

I think this modify is not a good solution, but it worked
