### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2103' in position

### ISSUE THREAD

**Issue by vasiauvi** [ebroecker/canmatrix#636]
I have an arxml file which contains on the Description attribute Chinese characters and other characters like degree Celsius. Because of this I get this error:

_Traceback (most recent call last):
  File "C:\Users\ursui\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ursui\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python_env\venv_PyTAWrapper\Scripts\canconvert.exe\__main__.py", line 7, in <module>
  File "d:\python_env\venv_pytawrapper\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\canmatrix\cli\convert.py", line 153, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\canmatrix\convert.py", line 331, in convert
    canmatrix.formats.dumpp(out_dbs, out_file_name, **options)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\canmatrix\formats\__init__.py", line 129, in dumpp
    dump(db, file_object, export_type, **options)
  File "d:\python_env\venv_pytawrapper\lib\site-packages\canmatrix\formats\__init__.py", line 104, in dump
    module_instance.dump(can_matrix_or_cluster, file_object, **options)  # type: ignore
  File "d:\python_env\venv_pytawrapper\lib\site-packages\canmatrix\formats\dbc.py", line 318, in dump
    f.write(signal_line.encode(dbc_export_encoding, ignore_encoding_errors))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2103' in position 54: ordinal not in range(256)_

Using first the canconvert --deleteSignalAttributes Description original.arxml final.arxml doesn't work. The final arxml can't be loaded with other tools like Autosar Explorer.

**Comment by ebroecker** [comment]
Hi @vasiauvi,

you are trying to convert `.arxml` to `.dbc`?

you could try the command line switch `--ignoreEncodingErrors`
