### ISSUE TITLE
Arxml -> dbc error

### ISSUE THREAD

**Issue by pansarna** [ebroecker/canmatrix#638]
Hi, 
I try to convert arxml to dbc, but I am getting following error: 

C:\>canconvert.exe aaaa.arxml out.dbc
ldf is not supported
INFO - convert - Importing aaaa.arxml ...
ERROR - arxml - No valid compu method found for isignal/systemsignal ISignalVoid_ACA_02_XIX_HCP1_CANFD02_0/SignalVoid_ACA_02_0 - check ARXML file!!
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\Scripts\canconvert-script.py", line 33, in <module>
    sys.exit(load_entry_point('canmatrix==0.9.5', 'console_scripts', 'canconvert')())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\cli\convert.py", line 153, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\convert.py", line 68, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\__init__.py", line 71, in loadp
    return load(fileObject, import_type, key, **options)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\__init__.py", line 88, in load
    dbs = module_instance.load(file_object, **options)  # type: ignore
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1959, in load
    result.update(decode_can_helper(ea, float_factory, ignore_cluster_info))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1852, in decode_can_helper
    frame = get_frame(frameTrig, ea, multiplex_translation, float_factory, headers_are_littleendian)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1595, in get_frame
    get_signals(pdu_sig_mapping, new_frame, ea, None, float_factory)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1103, in get_signals
    get_signalgrp_and_signals(isignal, isignal_array, frame, group_id, ea)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 989, in get_signalgrp_and_signals
    e2e_transform['data_ids'] = [int(x.text) for x in data_id_elems]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 989, in <listcomp>
    e2e_transform['data_ids'] = [int(x.text) for x in data_id_elems]
ValueError: invalid literal for int() with base 10: '0xad'

**Comment by pansarna** [comment]
It worked, thank you. :)
