### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by jtjart** [ebroecker/canmatrix#651]
When I try to convert a arxml-file to a dbc-file with the latest release I get following result:

```
canconvert source.arxml target.dbc
INFO - convert - Importing source.arxml ...
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\canconvert-script.py", line 33, in <module>
    sys.exit(load_entry_point('canmatrix==0.9.4.post13+g4f4a30a', 'console_scripts', 'canconvert')())
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\cli\convert.py", line 154, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\convert.py", line 68, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\__init__.py", line 71, in loadp
    return load(fileObject, import_type, key, **options)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\__init__.py", line 88, in load
    dbs = module_instance.load(file_object, **options)  # type: ignore
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1959, in load
    result.update(decode_can_helper(ea, float_factory, ignore_cluster_info))
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1852, in decode_can_helper
    frame = get_frame(frameTrig, ea, multiplex_translation, float_factory, headers_are_littleendian)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1595, in get_frame
    get_signals(pdu_sig_mapping, new_frame, ea, None, float_factory)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 1221, in get_signals
    unit_element = ea.get_child(isignal, "UNIT")
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\formats\arxml.py", line 206, in get_child
    raise "use follow_ref!"
TypeError: exceptions must derive from BaseException
```

**Comment by ebroecker** [comment]
Hi @jtjart ,

thanks for this report, will be fixed in pr #717
