### ISSUE TITLE
Problems with conversion between XLSX and DBC in merged files

### ISSUE THREAD

**Issue by rbakerbotelho** [ebroecker/canmatrix#698]
Hi, 

I have a XLSX file where, apparently, 3 dbcs were merged. I'm currently trying to convert the XLSX to DBC file, but I keep getting the same error. 

![image](https://user-images.githubusercontent.com/50106855/232912470-27bcd489-5045-43a9-98d8-d8ccf1cc9401.png)

`arxml is not supported                                                                                                                  
kcd is not supported
fibex is not supported
odx is not supported
Traceback (most recent call last):
  File "C:\Users\rodri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\canmatrix\convert.py", line 68, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "C:\Users\rodri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\canmatrix\formats\__init__.py", line 71, in loadp
    return load(fileObject, import_type, key, **options)
  File "C:\Users\rodri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\canmatrix\formats\__init__.py", line 90, in load
    dbs[key] = module_instance.load(file_object, **options)  # type: ignore
  File "C:\Users\rodri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\canmatrix\formats\xlsx.py", line 395, in load
    return xls_loader.load(filename, **options)
  File "C:\Users\rodri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\canmatrix\formats\xls.py", line 482, in load
    multiplex = int(mux.strip())
ValueError: invalid literal for int() with base 10: ''`

The xlsx file has three tabs. I saved each tab on a separated file each. I was able to convert both the second and third xlsx files to two dbcs.
However, I'm still getting the same error for the first tab/xlsx file. 

Any idea what could be causing such error on my excel file? I can't see anything wrong.

**Comment by ebroecker** [comment]
Hi @rbakerbotelho ,

seems something with the multiplexer is not ok.

I just can guess:

Do you have multiplexed Messages in first tab?
If so - have a look to the multiplexer values there.
Maybe a multiplexer-value is missing somewhere?

Eduard
