### ISSUE TITLE
Autosar 4.4 file failed to get converted to dbc format( no compmethod found fuzzy search in syssignal)

### ISSUE THREAD

**Issue by gsanthar** [ebroecker/canmatrix#702]
C:\work\CAN\ARXML>canconvert.exe TPV2_BECM_05082023_v1.arxml TPV2_BECM_05082023_v1.dbc
INFO - convert - Importing TPV2_BECM_05082023_v1.arxml ...
DEBUG - arxml - Read arxml ...
DEBUG - arxml -  Done

DEBUG - arxml - Build arTree ...
DEBUG - arxml -  Done

DEBUG - arxml - 29 frames in arxml...
DEBUG - arxml - 29 can-frame-triggering in arxml...
DEBUG - arxml - 0 SIGNAL-TO-PDU-MAPPINGS in arxml...
DEBUG - arxml - 446 I-SIGNAL-TO-I-PDU-MAPPING in arxml...
DEBUG - arxml - Busname: FZM_CAN_FD
DEBUG - arxml - 29 frames found in arxml
DEBUG - arxml - processing Frame: FT_AUTOSAR_NM_BECM
DEBUG - arxml - AUTOSAR_NM_BECM
DEBUG - arxml - No Compmethod found!! - try alternate scheme 1.
DEBUG - arxml - No Compmethod found!! - fuzzy search in syssignal.
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\work\CAN\ARXML\canconvert.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\canmatrix\cli\convert.py", line 237, in main
    canmatrix.convert.convert(infile, out_file_name, **cmdlineOptions.__dict__)
  File "c:\python27\lib\site-packages\canmatrix\convert.py", line 42, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "c:\python27\lib\site-packages\canmatrix\formats\__init__.py", line 74, in loadp
    return load(fileObject, import_type, key, **options)
  File "c:\python27\lib\site-packages\canmatrix\formats\__init__.py", line 91, in load
    dbs = module_instance.load(file_object, **options)  # type: ignore
  File "c:\python27\lib\site-packages\canmatrix\formats\arxml.py", line 1620, in load
    frame = get_frame(frameTrig, search_point, multiplex_translation, ns, float_factory)
  File "c:\python27\lib\site-packages\canmatrix\formats\arxml.py", line 1324, in get_frame
    get_signals(pdu_sig_mapping, new_frame, root_or_cache, ns, None, float_factory)
  File "c:\python27\lib\site-packages\canmatrix\formats\arxml.py", line 1162, in get_signals
    new_signal._initValue = float_factory(initvalue.text)
  File "c:\python27\lib\decimal.py", line 547, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "c:\python27\lib\decimal.py", line 3872, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: '0xff'

C:\work\CAN\ARXML>

**Comment by ebroecker** [comment]
did not hear anything new.
I'll close this issue, please create a new one, if this or anohter problem occures
