### ISSUE TITLE
Default value exception when converting `.sym`->`.dbc`

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#9]
I'm doing a little work on the tests starting with just generating all outputs for each provided input file type.  When it gets to `.sym`->`.dbf` I get an issue with a missing default value for a define.  My gut feeling is that this is an issue with the export and should be handled there, but I'm not certain.  Since you are much more familiar, what do you think?

```
Here's the error in the context of a direct manual call to `convert.py`.

altendky@tp:/epc/t/109/canmatrix$ git log -n 1
commit 46e7a32616c6865eef254a59d1bedfe70f066d73
Author: eduard <eduard@gmx.de>
Date:   Mon Nov 23 21:48:42 2015 +0100

    small documentation update (hopefully no german comments left)
altendky@tp:/epc/t/109/canmatrix$ ./convert.py AFE_CAN_ID247_FACTORY.sym AFE_CAN_ID247_FACTORY.dbf
Importing AFE_CAN_ID247_FACTORY.sym ... 
done

Exporting AFE_CAN_ID247_FACTORY.dbf ... 

26 Frames found
Traceback (most recent call last):
  File "./convert.py", line 93, in <module>
    ex.exportDbf(db, outfile)
  File "/epc/t/109/canmatrix/library/exportdbf.py", line 150, in exportDbf
    f.write('"' + type + '",' + define._definition.encode(dbfExportEncoding,'replace').replace(' ',',') + ',' + define._defaultValue + '\n')
TypeError: cannot concatenate 'str' and 'NoneType' objects
altendky@tp:/epc/t/109/canmatrix$ 
```

**Comment by ebroecker** [comment]
Yes - you are right. 
It is an export-issue. The solution is equal to the solution in exportdbc
